camel.springboot.name: SampleCamel

greeting: Hello World

# how often to trigger the timer
timer.period: 2000

# all access to actuator endpoints without security
management.security.enabled: false
# turn on actuator health check
endpoints:
  enabled: false
  health.enabled: true
